name: run-staging-tests
on:
  workflow_call:
  workflow_dispatch:

env:
  DB_URL: "example.com"
  PROJECT_BASE_DIR: "examplle"
  SONARCUBE_PROJECT_KEY: "example"
  SLACK_CHANNEL: "example"


jobs:
  staging-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Staging tests
        run: |
          cd ${{env.PROJECT_BASE_DIR}}
          ./gradlew clean integrationTests -Dbase_url="${{env.DB_URL}}"
      - name: Upload Staging test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: staging-tests-report
          path: tests/build/reports/tests/integrationTests
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ${{env.PROJECT_BASE_DIR}}
          args: >
            -Dsonar.projectKey=${{env.SONARCUBE_PROJECT_KEY}}
            -Dsonar.java.binaries=build/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFY }}
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          SLACK_USERNAME: GitHub
          SLACK_COLOR: ${{ job.status }}
