      - name: Log into registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        run: |
          docker build --no-cache -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:develop .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:develop

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Brew and kubelogin
        run: |
          brew install Azure/kubelogin/kubelogin

      - name: Log in with Azure
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Cluster Credentials
        run: |
          az aks get-credentials --name ${{ env.CLUSTER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}
          kubelogin convert-kubeconfig -l azurecli

      - name: Deploy Manifest
        run: |
          kubectl apply -f ./k8s/${{ env.DEPLOY_MANIFEST }}

      - name: Rollout restart deployment
        run: |
          kubectl rollout restart deployment ${{ env.DEPLOYMENT }} --namespace ${{ env.NAMESPACE }}

      - name: logout
        run: |
          az logout
        if: always()
