FROM golang

RUN mkdir /Go

WORKDIR /Go 

COPY ["main.go","kubernetes.go", "./"]

RUN go mod init main && go get -d . && go build kubernetes.go main.go

# FROM alpine:latest 

# COPY --from=0 /Go/kubernetes /usr/local/bin/

CMD ["./kubernetes"]